// electron/preload.cjs
// Plain CommonJS, not TypeScript: Electron's sandboxed preload scripts ignore
// package.json's "type": "module" and run without an ESM context at all
// (https://www.electronjs.org/docs/latest/tutorial/esm — preload scripts need
// .mjs for ESM, and sandboxed preload has no ESM context). This is the one
// file in the project that isn't native-TS, because the platform doesn't
// support it here, not because it was skipped.
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('promptBattle', {
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  changeFolder: () => ipcRenderer.invoke('change-folder'),
  attachPick: () => ipcRenderer.invoke('attach-pick'),
  attachPaths: (paths) => ipcRenderer.invoke('attach-paths', paths),
  attachData: (name, base64) => ipcRenderer.invoke('attach-data', name, base64),
  attachRemove: (id) => ipcRenderer.invoke('attach-remove', id),
  startRun: (options) => ipcRenderer.invoke('start-run', options),
  submitPrompt: (text) => ipcRenderer.send('submit-prompt', text),
  askAnswer: (answers) => ipcRenderer.invoke('ask-answer', answers),
  previewDamage: (prompt) => ipcRenderer.invoke('preview-damage', prompt),
  setPlanMode: (on) => ipcRenderer.invoke('set-plan-mode', on),
  serversList: () => ipcRenderer.invoke('servers-list'),
  serversKill: (pid) => ipcRenderer.invoke('servers-kill', pid),
  openLocal: (port) => ipcRenderer.invoke('open-local', port),
  onSaveAndClose: (callback) => ipcRenderer.on('save-and-close', () => callback()),
  saveAndCloseDone: (ok) => ipcRenderer.send('save-and-close-done', ok),
  stopTurn: () => ipcRenderer.invoke('stop-turn'),
  typingHit: (cpm, length) => ipcRenderer.invoke('typing-hit', cpm, length),
  claudeCapabilities: (cwd, refresh) => ipcRenderer.invoke('claude-capabilities', cwd, refresh),
  setClaudeSettings: (settings) => ipcRenderer.invoke('set-claude-settings', settings),
  mcpParse: (name, kind, value) => ipcRenderer.invoke('mcp-parse', name, kind, value),
  openLink: (key) => ipcRenderer.invoke('open-link', key),
  claudeSettingsInfo: () => ipcRenderer.invoke('claude-settings-info'),
  apiKeyInfo: () => ipcRenderer.invoke('api-key-info'),
  setApiKey: (key) => ipcRenderer.invoke('set-api-key', key),
  checkAuth: () => ipcRenderer.invoke('check-auth'),
  getUsage: () => ipcRenderer.invoke('get-usage'),
  movePath: (src, destDir) => ipcRenderer.invoke('move-path', src, destDir),
  importFiles: (sources, destDir) => ipcRenderer.invoke('import-files', sources, destDir),
  createEntry: (parentDir, name, kind) => ipcRenderer.invoke('create-entry', parentDir, name, kind),
  // Dropped OS files: Electron no longer exposes File.path to the page.
  pathForFile: (file) => webUtils.getPathForFile(file),
  listSessions: (cwd) => ipcRenderer.invoke('list-sessions', cwd),
  sessionHistory: (cwd, sessionId) => ipcRenderer.invoke('session-history', cwd, sessionId),
  listSlots: () => ipcRenderer.invoke('list-slots'),
  getFolderSession: (cwd) => ipcRenderer.invoke('get-folder-session', cwd),
  onBattleEvent: (callback) => {
    ipcRenderer.on('battle-event', (_event, data) => callback(data));
  },
  getFileIcon: (path) => ipcRenderer.invoke('get-file-icon', path),
  readFileContent: (path) => ipcRenderer.invoke('read-file-content', path),
  getSetupInfo: () => ipcRenderer.invoke('get-setup-info'),
  setModel: (model) => ipcRenderer.invoke('set-model', model),
  listTree: () => ipcRenderer.invoke('list-tree'),
  writeFile: (path, content) => ipcRenderer.invoke('write-file', path, content),
  setParty: (on) => ipcRenderer.invoke('set-party', on),
  getDaily: () => ipcRenderer.invoke('get-daily'),
  rankingList: (board) => ipcRenderer.invoke('ranking-list', board),
  rankingSubmit: (name) => ipcRenderer.invoke('ranking-submit', name),
  notify: (title, body) => ipcRenderer.send('notify', title, body),
  deleteSlot: (slot) => ipcRenderer.invoke('delete-slot', slot),
  rebirth: () => ipcRenderer.invoke('rebirth'),
  skillsList: () => ipcRenderer.invoke('skills-list'),
  journal: () => ipcRenderer.invoke('journal-get'),
  titleBuy: (id) => ipcRenderer.invoke('title-buy', id),
  titleWear: (id) => ipcRenderer.invoke('title-wear', id),
  codexStatus: () => ipcRenderer.invoke('codex-status'),
  codexLogin: () => ipcRenderer.invoke('codex-login'),
  skillSave: (skill) => ipcRenderer.invoke('skill-save', skill),
  skillDelete: (name) => ipcRenderer.invoke('skill-delete', name),
  checkUpdate: (force) => ipcRenderer.invoke('check-update', force),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, status) => callback(status)),
  openReleasePage: () => ipcRenderer.invoke('open-release-page'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
});
