#!/usr/bin/env node
// Generates electron/renderer/icons.js: the Lucide icons (ISC) the UI uses,
// and which emoji each one replaces. Only the needed icons are copied, so
// the 64 MB lucide-static package stays a dev dependency.
// Run after changing EMOJI below: `node scripts/build-icons.mjs`.
import { readFileSync, writeFileSync } from 'node:fs';

export const EMOJI = {
  '⚙️': 'settings', '⚙': 'settings', '🪙': 'coins', '💾': 'save', '⌨️': 'keyboard', '⌨': 'keyboard', '✕': 'x', '✗': 'x', '❌': 'circle-x',
  '🧙': 'wand-sparkles', '✅': 'circle-check', '✓': 'check', '✔️': 'check', '🗡': 'sword', '🗡️': 'sword', '⏳': 'hourglass', '🔄': 'refresh-cw',
  '📁': 'folder', '⚔️': 'swords', '⚔': 'swords', '👥': 'users', '🎲': 'dices', '⏹': 'circle-stop', '⏹️': 'circle-stop', '🤖': 'bot',
  '🏹': 'bow-arrow', '🩹': 'bandage', '🧪': 'flask-conical', '📖': 'book-open', '⚡': 'zap', '📅': 'calendar', '🔊': 'volume-2',
  '🔇': 'volume-x', '🎖': 'medal', '🎖️': 'medal', '⭐': 'star', '⏱': 'timer', '⏱️': 'timer', '⚠️': 'triangle-alert', '⚠': 'triangle-alert',
  '💥': 'flame', '🔨': 'hammer', '⚒': 'hammer', '⚒️': 'hammer', '👑': 'crown', '📝': 'file-pen', '✏️': 'pencil', '📊': 'chart-column',
  '📈': 'trending-up', '▶': 'play', '▶️': 'play', '🗨': 'message-circle', '🗨️': 'message-circle', '🔀': 'shuffle', '🏆': 'trophy',
  '🦅': 'bird', '✨': 'sparkles', '▾': 'chevron-down', '▴': 'chevron-up', '🟢': 'circle', '📄': 'file', '🎒': 'backpack', '📜': 'scroll',
  '🔑': 'key-round', '🧩': 'puzzle', '🔌': 'plug', '🪨': 'gem', '🧿': 'shield-check', '💨': 'wind', '📦': 'package', '🛡': 'shield',
  '🛡️': 'shield', '❔': 'circle-help', '⬆️': 'arrow-up', '⬇️': 'arrow-down', '🗑': 'trash-2', '🗑️': 'trash-2', '🔍': 'search',
  '🔒': 'lock', '❤️': 'heart', '🐉': 'flame', '🏔': 'mountain', '🏔️': 'mountain', '☄️': 'rocket', '📚': 'library', '🤐': 'mic-off',
  '⚀': 'dice-1', '⚁': 'dice-2', '⚂': 'dice-3', '⚃': 'dice-4', '⚄': 'dice-5', '⚅': 'dice-6', '💀': 'skull', '🎁': 'gift', '💰': 'hand-coins', '💣': 'bomb', '🤝': 'handshake', '📃': 'scroll-text', '💎': 'gem', '🔔': 'bell', '👻': 'ghost', '🎯': 'target',
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const names = [...new Set(Object.values(EMOJI))].sort();
  const icons = {};
  for (const name of names) {
    const svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, 'utf-8');
    icons[name] = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>')).replace(/\s*\n\s*/g, '');
  }
  writeFileSync(
    'electron/renderer/icons.js',
    `// Generated by scripts/build-icons.mjs — do not edit by hand.\n// Lucide icons (https://lucide.dev), ISC license.\nexport const ICONS = ${JSON.stringify(icons, null, 1)};\nexport const EMOJI_ICONS = ${JSON.stringify(EMOJI, null, 1)};\n`,
  );
  console.log(`${names.length} icons written`);
}
